In [1]:
import pandas as pd
acs = pd.read_csv("ACS_data10.csv",  index_col = "Community Area")
calls = pd.read_csv("311calls.csv",  index_col = "Community Area")
acscalls = acs.join(calls) #joining the acs data with 311 calls and saving as new dataframe, indexed on community area

acscalls.to_csv('acs_calls_merged.csv')
acscalls.head()

,GEOG,POP_25OV,HS,BACH,MEDINC,VACperc,PopOv25wBach,PopOv25wHS,Reports
Community Area,,,,,,,,,
14,Albany Park,34545,26212,10482,51968.84984,0.004454,0.303430,0.758778,27
57,Archer Heights,7944,5407,888,43393.53612,0.025773,0.111782,0.680639,6
34,Armour Square,10115,6636,2150,24336.46113,0.023159,0.212556,0.656055,2
70,Ashburn,26767,22201,5359,63573.16227,0.013212,0.200209,0.829417,38
71,Auburn Gresham,30659,25304,4273,29388.71473,0.050596,0.139372,0.825337,209

In [2]:
import pandas as pd
crimesformatted = pd.read_csv("crimes_formatted.csv",  index_col = "Community Area")
acscallz = pd.read_csv("acs_calls_merged.csv",  index_col = "Community Area")
final = crimesformatted.join(acscallz) #joining crime with the merged acs/311 data, indexed on community area

final.head()
final.to_csv('final.csv')

,Property,Violent,Primary Type,GEOG,POP_25OV,HS,BACH,MEDINC,VACperc,PopOv25wBach,PopOv25wHS,Reports
Community Area,,,,,,,,,,,,
1,1664,10770,12434,Rogers Park,37029,31167,15502,37223.34004,0.003832,0.418645,0.841692,4
2,2408,8811,11219,West Ridge,48333,40015,19004,46091.23435,0.005106,0.393189,0.827902,10
3,1747,10391,12138,Uptown,44870,40086,24740,45710.64553,0.005522,0.551371,0.893381,11
4,1280,5291,6571,Lincoln Square,32056,28766,18676,62933.97626,0.008872,0.582605,0.897367,20
5,1405,4223,5628,North Center,25565,23859,17419,92663.61257,0.006447,0.681361,0.933268,21